sdk:
  - changed-files:
      - any-glob-to-any-file: "src/content/docs/developer-tools/sdks/**/*"
"security and privacy":
  - changed-files:
      - any-glob-to-any-file: "src/content/docs/trust-center/**/*"
