openapi: 3.0.0
info:
  version: '1'
  title: Kinde Frontend API
  description: >
    To access the OAuth endpoint, you will need to use a user token. This can be
    obtained when your users sign in via the methods you've setup in Kinde (e.g.
    Google, passwordless, etc). Find this using the getToken command in the
    relevant SDK.
  termsOfService: https://docs.kinde.com/trust-center/agreements/terms-of-service/
  contact:
    name: Kinde Support Team
    email: support@kinde.com
    url: https://docs.kinde.com
servers:
  - url: https://{subdomain}.kinde.com
    variables:
      subdomain:
        default: your_kinde_subdomain
        description: The subdomain generated for your business on Kinde.
tags:
  - name: OAuth
    x-displayName: OAuth
paths:
  /oauth2/v2/user_profile:
    get:
      tags:
        - OAuth
      operationId: getUserProfileV2
      summary: Get user profile
      description: >
        This endpoint returns a user's ID, names, profile picture URL and email
        of the currently logged in user.
      responses:
        '200':
          description: Details of logged in user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_profile_v2'
        '403':
          description: Invalid credentials.
        '429':
          description: Request was throttled.
      security:
        - kindeBearerAuth: []
  /oauth2/introspect:
    post:
      tags:
        - OAuth
      operationId: tokenIntrospection
      description: Retrieve information about the provided token.
      summary: Get token details
      requestBody:
        description: Token details.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                token:
                  description: The token to be introspected.
                  type: string
                token_type:
                  type: string
                  description: The provided token's type.
      responses:
        '200':
          description: Details of the token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token_introspect'
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/token_introspect'
        '401':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token_error_response'
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/token_error_response'
        '403':
          description: Invalid credentials.
        '429':
          description: Request was throttled.
      security:
        - kindeBearerAuth: []
  /oauth2/revoke:
    post:
      tags:
        - OAuth
      operationId: tokenRevocation
      description: Revoke a previously issued token.
      summary: Revoke token
      requestBody:
        description: Details of the token to be revoked.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                token:
                  description: The token to be revoked.
                  type: string
                client_id:
                  type: string
                  description: The identifier for your client.
                client_secret:
                  type: string
                  description: The secret associated with your client.
      responses:
        '200':
          description: Token successfully revoked.
        '401':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token_error_response'
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/token_error_response'
        '403':
          description: Invalid credentials.
        '429':
          description: Request was throttled.
      security:
        - kindeBearerAuth: []
components:
  schemas:
    token_introspect:
      type: object
      properties:
        active:
          type: boolean
          description: Indicates the status of the token.
        aud:
          type: array
          description: Array of intended token recipients.
          items:
            type: string
        client_id:
          type: string
          description: Identifier for the requesting client.
        exp:
          type: string
          description: Token expiration timestamp.
        iat:
          type: string
          description: Token issuance timestamp.
    token_error_response:
      type: object
      properties:
        error:
          type: string
          description: Error.
        error_description:
          type: string
          description: The error description.
    user_profile_v2:
      type: object
      properties:
        sub:
          type: string
          description: Unique ID of the user in Kinde.
          example: kp_c3143a4b50ad43c88e541d9077681782
        provided_id:
          type: string
          description: >-
            Value of the user's ID in a third-party system when the user is
            imported into Kinde.
          example: some_external_id
          nullable: true
        name:
          type: string
          description: User's first and last name separated by a space.
          example: John Snow
        given_name:
          type: string
          description: User's first name.
          example: John
        family_name:
          type: string
          description: User's last name.
          example: Snow
        updated_at:
          type: integer
          description: Date the user was last updated at (In Unix time).
          example: 1612345678
        email:
          type: string
          description: User's email address if available.
          example: john.snow@example.com
        email_verified:
          type: boolean
          description: Whether the user's email address has been verified.
          example: true
        picture:
          type: string
          description: URL that point's to the user's picture or avatar
          example: https://example.com/john_snow.jpg
          nullable: true
        preferred_username:
          type: string
          description: User's preferred username.
          example: john_snow
          nullable: true
        id:
          type: string
          description: Unique ID of the user in Kinde
          example: kp_c3143a4b50ad43c88e541d9077681782
  securitySchemes:
    kindeBearerAuth:
      description: >
        To access the OAuth endpoint, you will need to use a user token. This
        can be obtained when your users sign in via the methods you've setup in
        Kinde (e.g. Google, passwordless, etc). Find this using the getToken
        command in the relevant SDK.
      type: http
      scheme: bearer
      bearerFormat: JWT
